
default_job = "run"
[jobs]
[jobs.test]
command = ["cargo", "test", "--color", "always"]

[jobs.format]
command = ["cargo", "fmt"]
need_stdout = false
on_success = "back" # so that we don't open the browser at each change
 
[jobs.run]
command = ["cargo", "r", "--color", "always", "--", "--help"]
need_stdout = true

[keybindings]
f = "job:format"
t = "job:test"
r = "job:run"
