[package]
name = "caesor_cipher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.8", features = ["derive"] }
colored="*"
trycmd = "0.13.7"
assert_cmd = "2.0.4"
